# -*- coding: utf-8 -*-
"""Week 2 assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ImuY7Vs24ZUMJa_Mr8rcehRMI-pu2v9

In a cohort study 752 patients with renal failure received a renal transplantation and were followed for graft-rejection. The Rdata-set ‘renaltx.Rdata Download renaltx.Rdata’ contains some data of this study:



outcome:

            gstatus             = graft-rejection (=1) or not (=0)

            gsurv                = number of months the patient was followed until rejection or censoring

            pstatus             = patient-status at end of follow-up (1=died, 0=alive)

            psurv                = number of months the patient was followed until death or censoring



covariates/risk factors:

            acclft              = age of the patient at transplantation (years)

            dgf                   = delayed graft function (dgf or 0=no dgf)

            aantalre           = number of acute rejection-treatments during the first 6 months post-transplantation (0, 1, 2 or 3)

            creat                = serum creatinine at six-weeks post-transplantation (mumol/L) (marker of kidney-function)

            predias            = diastolic bloodpressure pre-transplantation

            prac                 = panel reactive antibodies (marker of inflammation)

            uprotein           = protein in urine at six-weeks post-transplantation  (geen,  sp/+,  >+) (marker of kidney function)

            cregsh              = number of cross-reactive groups (public HLA epitopes) of the major histocompatibility complex class I shared between donor

                                        and recipient



Please, analyze this dataset and report on the association between the risk factors and the risk of graft-rejection.

Notice that there are some missing values in the dataset and also notice that some quantitative variables have really not-normal-shaped distributions.



The principal aim is to evaluate whether acclft, dgf, aantalre, creat, predias, prac, uprotein and cregsh are associated with risk of graft-rejection. The assignment for this week is to analyze the shape of the association between the various risk factors and the risk of graft-rejection. Perform both univariable and multivariable regression analysis.



Make a reasoned decision on the appropriate regression model,

list the assumptions involved in that regression model and check whether the assumptions fit to the current data. Look in particular at the appropriateness of the linearity assumption that is made by default for the quantitative risk factors. Also consider the competing effect of patient-death.



Report your results in a results-section of a scientific paper and send this to a.h.zwinderman@amsterdamUMC.nl or upload it into Canvas before 09.00 hrs on Monday November 10, 2025. Your results-section will be used (and scored) for the Academic Skills module and therefore your report must be textual (i.e. not a set of slides) and the number of tables and graphs must be limited to, say, three. Other tables and graphs may be attached as supplemental material to the results-section.
"""

#%pip install pyreadstat

import pandas as pd
import numpy as np
# import pyreadstat
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns
# from lifelines import CoxPHFitter, KaplanMeierFitter
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve, brier_score_loss
from scipy.stats import ttest_ind, chi2_contingency

#Read the file renaltx.csv
#uploaded = files.upload()

# === 2. LOAD DATA ============================================================
df = pd.read_csv('renaltx.csv')

print(df.head())
# print(df.info())

"""# Task
Perform univariable regression analysis with `gstatus` as the dependent variable. Structure the results into a table with the specified columns: 'Variable', 'gstatus (0)', 'gstatus (1)', 'P-value', and 'Missing'. Format continuous variables as 'mean (sd)' and categorical variables as 'count (%)'.

## Data preparation

### Subtask:
Separate the dataset based on the `gstatus` variable (0 and 1) to compare the groups.

**Reasoning**:
Separate the dataframe into two based on the value of the 'gstatus' column.
"""

df_gstatus_0 = df[df['gstatus'] == 0].copy()
df_gstatus_1 = df[df['gstatus'] == 1].copy()

"""## Univariable analysis

### Subtask:
For each risk factor, perform the appropriate statistical test (t-test for continuous, chi-squared for categorical) to compare the `gstatus` groups.

**Reasoning**:
Identify continuous and categorical variables and perform appropriate statistical tests to compare the gstatus groups.
"""

# Identify continuous and categorical variables
continuous_vars = ['acclft', 'creat', 'predias', 'prac', 'cregsh']
categorical_vars = ['dgf', 'aantalre', 'uprotein']

# Initialize dictionaries to store p-values
p_values = {}

# Perform t-tests for continuous variables
for var in continuous_vars:
    # Drop NaN values for the t-test
    group0 = df_gstatus_0[var].dropna()
    group1 = df_gstatus_1[var].dropna()
    if len(group0) > 1 and len(group1) > 1: # Ensure there are enough samples
        ttest_result = ttest_ind(group0, group1)
        p_values[var] = ttest_result.pvalue
    else:
        p_values[var] = np.nan # Not enough data to perform test

# Perform chi-squared tests for categorical variables
for var in categorical_vars:
    # Create a contingency table
    contingency_table = pd.crosstab(df[var], df['gstatus'])
    if contingency_table.shape[0] > 1 and contingency_table.shape[1] > 1: # Ensure table is not 1xN or Nx1
        chi2, p, dof, expected = chi2_contingency(contingency_table)
        p_values[var] = p
    else:
        p_values[var] = np.nan # Not enough categories to perform test

print(p_values)

"""## Calculate summary statistics

### Subtask:
Calculate the mean (standard deviation) for continuous variables and count (percentage) for categorical variables for each `gstatus` group.

**Reasoning**:
Calculate the mean (standard deviation) for continuous variables and count (percentage) for categorical variables for each `gstatus` group and store them in a dictionary.
"""

summary_stats = {}

continuous_vars = ['acclft', 'creat', 'predias', 'prac', 'cregsh']
categorical_vars = ['dgf', 'aantalre', 'uprotein']

for var in continuous_vars:
    summary_stats[var] = {
        'gstatus_0': f"{df_gstatus_0[var].mean():.2f} ({df_gstatus_0[var].std():.2f})",
        'gstatus_1': f"{df_gstatus_1[var].mean():.2f} ({df_gstatus_1[var].std():.2f})"
    }

for var in categorical_vars:
    summary_stats[var] = {}
    total_0 = len(df_gstatus_0)
    total_1 = len(df_gstatus_1)
    for category in df[var].unique():
        if pd.isna(category):
            continue
        count_0 = df_gstatus_0[df_gstatus_0[var] == category].shape[0]
        percentage_0 = (count_0 / total_0) * 100 if total_0 > 0 else 0
        count_1 = df_gstatus_1[df_gstatus_1[var] == category].shape[0]
        percentage_1 = (count_1 / total_1) * 100 if total_1 > 0 else 0
        summary_stats[var][category] = {
            'gstatus_0': f"{count_0} ({percentage_0:.2f}%)",
            'gstatus_1': f"{count_1} ({percentage_1:.2f}%)"
        }

print(summary_stats)

"""## Count missing values

### Subtask:
Determine the number of missing values for each variable.

**Reasoning**:
Calculate the number of missing values for each variable in the DataFrame.
"""

missing_values = df.isnull().sum()
print(missing_values)

"""## Create results table

### Subtask:
Structure the calculated statistics, p-values, and missing value counts into a pandas DataFrame with the columns 'Variable', 'gstatus (0)', 'gstatus (1)', 'P-value', and 'Missing'.

**Reasoning**:
Structure the calculated statistics, p-values, and missing value counts into a pandas DataFrame.
"""

results_list = []

continuous_vars = ['acclft', 'creat', 'predias', 'prac', 'cregsh']
categorical_vars = ['dgf', 'aantalre', 'uprotein']

for var in continuous_vars:
    results_list.append({
        'Variable': var,
        'gstatus (0)': summary_stats[var]['gstatus_0'],
        'gstatus (1)': summary_stats[var]['gstatus_1'],
        'P-value': f"{p_values.get(var, np.nan):.4f}",
        'Missing': missing_values.get(var, 0)
    })

for var in categorical_vars:
    for category, stats in summary_stats[var].items():
        results_list.append({
            'Variable': f"{var}: {category}",
            'gstatus (0)': stats['gstatus_0'],
            'gstatus (1)': stats['gstatus_1'],
            'P-value': f"{p_values.get(var, np.nan):.4f}" if category == list(summary_stats[var].keys())[0] else '', # Only show p-value once per variable
            'Missing': missing_values.get(var, 0) if category == list(summary_stats[var].keys())[0] else '' # Only show missing once per variable
        })

results_df = pd.DataFrame(results_list)
display(results_df)

"""## Format table

### Subtask:
Format the continuous and categorical variables in the table as requested.

**Reasoning**:
Format the columns 'gstatus (0)', 'gstatus (1)', and 'P-value' in the results_df as specified, ensuring the correct number of decimal places and handling potential non-numeric values before conversion.
"""

# Function to safely convert to float and format
def safe_float_format(value, decimals):
    try:
        # Attempt to convert to float
        float_value = float(value)
        return f"{float_value:.{decimals}f}"
    except (ValueError, TypeError):
        # Return original value if conversion fails
        return value

# Format continuous variables in 'gstatus (0)' and 'gstatus (1)'
continuous_vars_in_table = results_df[results_df['Variable'].isin(continuous_vars)]['Variable'].tolist()
for var in continuous_vars_in_table:
    index = results_df[results_df['Variable'] == var].index[0]
    mean_sd_0 = results_df.loc[index, 'gstatus (0)'].split(' ')
    results_df.loc[index, 'gstatus (0)'] = f"{float(mean_sd_0[0]):.2f} ({float(mean_sd_0[1].strip('()')):.2f})"

    mean_sd_1 = results_df.loc[index, 'gstatus (1)'].split(' ')
    results_df.loc[index, 'gstatus (1)'] = f"{float(mean_sd_1[0]):.2f} ({float(mean_sd_1[1].strip('()')):.2f})"


# Format categorical variables in 'gstatus (0)' and 'gstatus (1)'
for var in categorical_vars:
    for index, row in results_df[results_df['Variable'].str.startswith(var + ':')].iterrows():
        count_perc_0 = row['gstatus (0)'].split(' ')
        count_0 = int(count_perc_0[0])
        percentage_0 = float(count_perc_0[1].strip('()%'))
        results_df.loc[index, 'gstatus (0)'] = f"{count_0} ({percentage_0:.2f}%)"

        count_perc_1 = row['gstatus (1)'].split(' ')
        count_1 = int(count_perc_1[0])
        percentage_1 = float(count_perc_1[1].strip('()%'))
        results_df.loc[index, 'gstatus (1)'] = f"{count_1} ({percentage_1:.2f}%)"


# Format 'P-value' column
results_df['P-value'] = results_df['P-value'].apply(lambda x: safe_float_format(x, 4))

# Ensure 'Missing' column is integer
results_df['Missing'] = pd.to_numeric(results_df['Missing'], errors='coerce').fillna(0).astype(int)

display(results_df)

"""## Summary:

### Data Analysis Key Findings

*   The variable `creat` showed a statistically significant difference between `gstatus` groups (P-value = 0.0031).
*   The variable `cregsh` showed a statistically significant difference between `gstatus` groups (P-value = 0.0036).
*   The categorical variable `aantalre` exhibited a highly statistically significant difference between the groups (P-value = 2.357e-05).
*   The categorical variable `uprotein` also showed a statistically significant difference between the groups (P-value = 0.0089).
*   Variables `acclft`, `predias`, and `dgf` did not show statistically significant differences between the `gstatus` groups (P-values > 0.05).
*   Missing values were observed in `dgf` (14), `creat` (1), `predias` (4), `uprotein` (18), and `cregsh` (17).

### Insights or Next Steps

*   Variables with significant p-values (`creat`, `cregsh`, `aantalre`, `uprotein`) should be considered as potential predictors in a multivariable model.
*   Investigate the patterns of missing data for variables with significant counts to determine appropriate handling strategies if needed for further analysis.

# Task
Perform univariable regression analysis with `gstatus` as the dependent variable. Structure the results into a table with the specified columns: 'Variable', 'gstatus (0)', 'gstatus (1)', 'Log OR (SE)', 'P-value', and 'Missing'. Format continuous variables as 'mean (sd)' and categorical variables as 'count (%)'.

## Univariable analysis

### Subtask:
For each risk factor, perform the appropriate statistical test (t-test for continuous, chi-squared for categorical) to compare the `gstatus` groups and perform univariable logistic regression to obtain Log OR (SE) and p-values.

**Reasoning**:
Initialize dictionaries to store p-values and logistic regression results and then iterate through continuous and categorical variables to perform statistical tests and univariable logistic regressions.
"""

# Initialize dictionaries to store results
p_values = {}
log_or_se = {}

continuous_vars = ['acclft', 'creat', 'predias', 'prac', 'cregsh']
categorical_vars = ['dgf', 'aantalre', 'uprotein']

# Perform statistical tests and logistic regression for continuous variables
for var in continuous_vars:
    # T-test for continuous variables
    group0 = df_gstatus_0[var].dropna()
    group1 = df_gstatus_1[var].dropna()
    if len(group0) > 1 and len(group1) > 1:
        ttest_result = ttest_ind(group0, group1)
        p_values[var] = ttest_result.pvalue
    else:
        p_values[var] = np.nan

    # Univariable logistic regression for continuous variables
    try:
        model = smf.logit(f'gstatus ~ {var}', data=df.dropna(subset=[var, 'gstatus'])).fit()
        log_or_se[var] = {'log_or': model.params[var], 'se': model.bse[var], 'p_value': model.pvalues[var]}
    except Exception as e:
        log_or_se[var] = {'log_or': np.nan, 'se': np.nan, 'p_value': np.nan}
        print(f"Could not fit logistic regression for {var}: {e}")


# Perform statistical tests and logistic regression for categorical variables
for var in categorical_vars:
    # Chi-squared test for categorical variables
    contingency_table = pd.crosstab(df[var], df['gstatus'])
    if contingency_table.shape[0] > 1 and contingency_table.shape[1] > 1:
        chi2, p, dof, expected = chi2_contingency(contingency_table)
        p_values[var] = p
    else:
        p_values[var] = np.nan

    # Univariable logistic regression for categorical variables
    try:
        # Use C() for categorical variables in formula
        model = smf.logit(f'gstatus ~ C({var})', data=df.dropna(subset=[var, 'gstatus'])).fit()
        log_or_se[var] = {}
        # Exclude intercept
        for param in model.params.index:
            if param != 'Intercept':
                log_or_se[var][param] = {'log_or': model.params[param], 'se': model.bse[param], 'p_value': model.pvalues[param]}
    except Exception as e:
        log_or_se[var] = {'log_or': np.nan, 'se': np.nan, 'p_value': np.nan}
        print(f"Could not fit logistic regression for {var}: {e}")

print("P-values from statistical tests:")
print(p_values)
print("\nLog OR and SE from univariable logistic regression:")
print(log_or_se)

"""## Create results table

### Subtask:
Structure the calculated statistics, Log OR (SE), p-values, and missing value counts into a pandas DataFrame with the columns 'Variable', 'gstatus (0)', 'gstatus (1)', 'Log OR (SE)', 'P-value', and 'Missing'.

**Reasoning**:
Structure the calculated statistics, Log OR (SE), p-values, and missing value counts into a pandas DataFrame.
"""

results_list = []

continuous_vars = ['acclft', 'creat', 'predias', 'prac', 'cregsh']
categorical_vars = ['dgf', 'aantalre', 'uprotein']

# Iterate through continuous variables
for var in continuous_vars:
    log_or = log_or_se.get(var, {}).get('log_or', np.nan)
    se = log_or_se.get(var, {}).get('se', np.nan)
    p_value_lr = log_or_se.get(var, {}).get('p_value', np.nan)

    results_list.append({
        'Variable': var,
        'Data Type': 'mean (SD)', # Assuming mean (SD) for continuous for now
        'gstatus (0)': summary_stats[var]['gstatus_0'],
        'gstatus (1)': summary_stats[var]['gstatus_1'],
        'P-value': f"{p_value_lr:.4f}" if not np.isnan(p_value_lr) else '',
        'Missing': missing_values.get(var, 0),
        'Log OR (SE)': f"{log_or:.4f} ({se:.4f})" if not np.isnan(log_or) and not np.isnan(se) else ''
    })

# Iterate through categorical variables
for var in categorical_vars:
    # Get the list of categories for this variable from summary_stats to maintain order
    categories_in_summary = list(summary_stats[var].keys())

    for i, category in enumerate(categories_in_summary):
        # Construct the parameter name as it appears in log_or_se for categorical variables
        param_name = f'C({var})[T.{category}]'
        log_or = log_or_se.get(var, {}).get(param_name, {}).get('log_or', np.nan)
        se = log_or_se.get(var, {}).get(param_name, {}).get('se', np.nan)
        p_value_lr = log_or_se.get(var, {}).get(param_name, {}).get('p_value', np.nan)

        results_list.append({
            'Variable': f"{var}: {category}",
            'Data Type': 'n (%)', # Assuming n (%) for categorical
            'gstatus (0)': summary_stats[var][category]['gstatus_0'],
            'gstatus (1)': summary_stats[var][category]['gstatus_1'],
            'P-value': f"{p_value_lr:.4f}" if not np.isnan(p_value_lr) and i > 0 else '', # Only show p-value for non-reference categories
            'Missing': missing_values.get(var, 0) if i == 0 else '', # Only show missing once per variable
            'Log OR (SE)': f"{log_or:.4f} ({se:.4f})" if not np.isnan(log_or) and not np.isnan(se) else ''
        })

results_df = pd.DataFrame(results_list)
display(results_df)

"""## Format table

### Subtask:
Format the continuous and categorical variables and the 'Log OR (SE)' and 'P-value' columns in the table as requested.

**Reasoning**:
Format the columns 'gstatus (0)', 'gstatus (1)', 'Log OR (SE)', 'P-value', and 'Missing' in the results_df as specified, ensuring the correct number of decimal places and handling potential non-numeric values before conversion.
"""

# Function to safely convert to float and format
def safe_float_format(value, decimals):
    try:
        # Attempt to convert to float
        float_value = float(value)
        return f"{float_value:.{decimals}f}"
    except (ValueError, TypeError):
        # Return original value if conversion fails
        return value

# Format 'P-value' column
results_df['P-value'] = results_df['P-value'].apply(lambda x: safe_float_format(x, 4))

# Ensure 'Missing' column is integer
results_df['Missing'] = pd.to_numeric(results_df['Missing'], errors='coerce').fillna(0).astype(int)

display(results_df)

"""## Summary:

### Data Analysis Key Findings

*   Continuous variables (`acclft`, `creat`, `predias`, `prac`, `cregsh`) were summarized by mean (sd) for each `gstatus` group. Categorical variables (`dgf`, `aantalre`, `uprotein`) were summarized by count (%) for each category within each `gstatus` group.
*   Missing value counts were calculated for each variable. For categorical variables, the missing count is listed only once per variable.
*   Univariable logistic regression was performed for each variable against `gstatus`. The table includes the Log Odds Ratio (Log OR) and its standard error (SE) for each variable or category (compared to the reference category for categorical variables).
*   P-values from the univariable logistic regression were calculated and formatted to four decimal places. For categorical variables, p-values are shown only for non-reference categories.

### Insights or Next Steps

*   The univariable analysis table provides a clear overview of the association between each variable and `gstatus`. Variables with statistically significant p-values (e.g., < 0.05) warrant further investigation in multivariable analysis.
*   Consider building a multivariable logistic regression model including the significant variables from the univariable analysis to assess their independent effects on `gstatus`.

# MICE imputation

TO DO: Perform Rubin's rule to pool results.
This is preperation for multivariable regression
"""

df0 = pd.read_csv('imputed_data_0.csv')
display(df0.head())
df1 = pd.read_csv('imputed_data_1.csv')
display(df1.head())
df2 = pd.read_csv('imputed_data_2.csv')
display(df2.head())
df3 = pd.read_csv('imputed_data_3.csv')
display(df3.head())
df4 = pd.read_csv('imputed_data_4.csv')
display(df4.head())